# Generated by Django 4.2.2 on 2023-06-10 20:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_info', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_overlay_text', wagtail.fields.RichTextField()),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=512)),
                ('alignment', models.CharField(choices=[('left', 'Left aligned'), ('center', 'Centered'), ('right', 'Right aligned')], default='left', max_length=6)),
                ('banner_priority', models.IntegerField(default=0, help_text='Higher banner appear earlier in series')),
                ('draft', models.BooleanField(default=True)),
                ('show_on_platform', models.BooleanField(default=True, help_text='Show on CG&T')),
                ('show_on_individual_site', models.BooleanField(default=True, help_text='If you have a custom site')),
                ('on_site_priority', models.IntegerField(default=0, help_text='Higher banner appear earlier in series')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.DateTimeField()),
                ('content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('attributes', models.ManyToManyField(to='game_info.attribute')),
                ('editions', models.ManyToManyField(to='game_info.edition')),
                ('factions', models.ManyToManyField(to='game_info.faction')),
                ('formats', models.ManyToManyField(to='game_info.format')),
                ('games', models.ManyToManyField(to='game_info.game')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
