# Generated by Django 4.2.2 on 2023-06-10 20:00

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IC', 'Integration Charge'), ('CC', 'Collected from Customer'), ('DC', 'Charge for Custom Development'), ('PO', 'A payment to the partner'), ('PI', 'A payment collected from the partner'), ('O?', 'Other')], default=None, max_length=3, null=True, verbose_name='type')),
                ('email_at_time_of_event', models.EmailField(blank=True, max_length=254, null=True)),
                ('timestamp', models.DateTimeField()),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('subtotal', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True)),
                ('processing_fee_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('processing_fee', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Fees from 3rd party services, generally for payouts', max_digits=14, null=True)),
                ('platform_fee_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('platform_fee', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Fees from the platform', max_digits=14, null=True)),
                ('final_total_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('final_total', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14)),
                ('applied_to_account', models.BooleanField(default=False)),
                ('balance_after_apply_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('balance_after_apply', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='USD', max_digits=14, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pledge_month', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_start', models.DateField()),
                ('finalized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['statement_start'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=8)),
            ],
        ),
    ]
