# Generated by Django 4.2.2 on 2023-06-10 20:00

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfc_cat_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_number', models.CharField(blank=True, max_length=200, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=200, null=True)),
                ('msrp_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('msrp', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('map_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('map', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('dist_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('dist_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('dist_barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('dist_description', models.TextField(null=True)),
                ('quantity_per_pack', models.IntegerField(blank=True, null=True)),
                ('weight_lbs', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('manually_entered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=200)),
                ('expected_filename', models.CharField(blank=True, max_length=200, null=True)),
                ('individual_warehouse_files', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['dist_name'],
            },
        ),
        migrations.CreateModel(
            name='DistributorInventoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='media/')),
                ('processing', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(blank=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=200)),
                ('warehouse_filename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemWarehouseAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfc_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerAbbreviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_prefix', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('cost_per_item_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('cost_per_item', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=8, null=True)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('received_quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('line_number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('percent_of_msrp', models.IntegerField(default=100)),
                ('use_MAP', models.BooleanField(default=False, help_text='Uses the MAP, if available, instead of the MSRP')),
            ],
        ),
        migrations.CreateModel(
            name='TradeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('date', models.DateField(null=True)),
                ('po_number', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('archived', models.BooleanField(default=False)),
                ('amount_charged_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('amount_charged', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('subtotal', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor')),
            ],
        ),
    ]
