# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('intake', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.publisher'),
        ),
        migrations.AddField(
            model_name='poline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='intake.purchaseorder'),
        ),
        migrations.AddField(
            model_name='manufacturerbarcode',
            name='mfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.manufacturer'),
        ),
        migrations.AddField(
            model_name='manufacturerabbreviation',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.distributor'),
        ),
        migrations.AddField(
            model_name='manufacturerabbreviation',
            name='mfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.manufacturer'),
        ),
        migrations.AddField(
            model_name='itemwarehouseavailability',
            name='based_on_file',
            field=models.ManyToManyField(to='intake.DistributorInventoryFile'),
        ),
        migrations.AddField(
            model_name='itemwarehouseavailability',
            name='dist_item',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='intake.distitem'),
        ),
        migrations.AddField(
            model_name='itemwarehouseavailability',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.distributorwarehouse'),
        ),
        migrations.AddField(
            model_name='distributorwarehouse',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor'),
        ),
        migrations.AddField(
            model_name='distributorinventoryfile',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor'),
        ),
        migrations.AddField(
            model_name='distributorinventoryfile',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.distributorwarehouse'),
        ),
        migrations.AddField(
            model_name='distitem',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.distributor'),
        ),
        migrations.AddField(
            model_name='distitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.manufacturer'),
        ),
        migrations.AddField(
            model_name='distitem',
            name='trade_range',
            field=models.ManyToManyField(related_name='contains', to='intake.TradeRange'),
        ),
        migrations.AddField(
            model_name='categorymap',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.Category'),
        ),
        migrations.AddField(
            model_name='categorymap',
            name='dist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.distributor'),
        ),
        migrations.AddField(
            model_name='categorymap',
            name='mfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.manufacturer'),
        ),
        migrations.AlterIndexTogether(
            name='manufacturerbarcode',
            index_together={('mfc', 'barcode_prefix')},
        ),
    ]
