# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfund', '0002_initial'),
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPack',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8, null=True)),
                ('default_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('default_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8)),
                ('enable_discounts', models.BooleanField(default=True)),
                ('pay_what_you_want', models.BooleanField(default=False, help_text='This makes price the minimum the user has to pay, and default price the amount the form defaults to')),
                ('grant_to_crowdfund_rewards', models.ManyToManyField(blank=True, related_name='digital_packs', to='crowdfund.Reward')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('pay_what_you_want', models.BooleanField(default=False, help_text='This makes price the minimum the user has to pay, and default price the amount the form defaults to')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='PackEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('added_from_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GrantedPackEntitlements', to='checkout.cart')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PackEntitlements', to='packs.digitalpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PackEntitlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
