# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalpack',
            name='grant_to_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='digital_packs', to='subscriptions.SubscriptionPack'),
        ),
    ]
