# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitalitems', '0004_initial'),
        ('user_list', '0001_initial'),
        ('packs', '0002_digitalpack_grant_to_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalpack',
            name='grant_to_user_lists',
            field=models.ManyToManyField(blank=True, related_name='digital_packs', to='user_list.UserList'),
        ),
        migrations.AddField(
            model_name='digitalpack',
            name='pack_contents',
            field=models.ManyToManyField(blank=True, related_name='packs', to='digitalitems.DigitalItem'),
        ),
        migrations.AddField(
            model_name='digitalpack',
            name='suggested_contents',
            field=models.ManyToManyField(blank=True, to='digitalitems.DigitalItem'),
        ),
    ]
