# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('inventory_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreportlocation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='inventoryreportline',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_report.inventoryreportlocation'),
        ),
        migrations.AddField(
            model_name='inventoryreportline',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_lines', to='inventory_report.inventoryreport'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
    ]
