# Generated by Django 4.2.2 on 2023-06-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.CharField(max_length=300, unique=True)),
                ('email_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.emailaddress')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='UserListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_into_emails', models.BooleanField(default=False)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to=settings.AUTH_USER_MODEL)),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='user_list.userlist')),
            ],
        ),
        migrations.CreateModel(
            name='EmailInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_sent', models.BooleanField(default=False, verbose_name=user_list.models.EmailImport)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user_list.emailimport')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_list.userlist')),
            ],
        ),
    ]
