# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq_cat_id', models.CharField(max_length=30)),
                ('sq_cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SquareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_aid', models.CharField(max_length=200)),
                ('square_token', models.CharField(max_length=200)),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='SquareInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=200)),
                ('variation_id', models.CharField(max_length=200)),
                ('category_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('local_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.inventoryitem')),
                ('sq_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squarelink.squarelink')),
            ],
        ),
    ]
