# Generated by Django 4.2.2 on 2023-06-10 20:00

import digitalitems.azure_storage
import digitalitems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_name', models.CharField(blank=True, max_length=200, null=True)),
                ('torrent_file', models.FileField(blank=True, max_length=500, null=True, upload_to='media/')),
                ('b2_file', models.FileField(max_length=500, upload_to='media/')),
                ('azure_file', models.FileField(max_length=500, null=True, storage=digitalitems.azure_storage.PrivateAzureStorage, upload_to=digitalitems.models.get_upload_hash_path)),
                ('preview_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='media/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
            ],
        ),
    ]
