# Generated by Django 3.2.16 on 2022-11-22 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalitems', '0001_initial'),
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('download_date', models.DateField(verbose_name='Date Available for download')),
                ('pay_what_you_want', models.BooleanField(default=False, help_text='This makes price the minimum the user has to pay, and default price the amount the form defaults to')),
                ('enable_download_all', models.BooleanField(default=True, help_text='Show the Download All Button')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='UserDownloadableHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('downloadable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='digitalitems.downloadable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadable_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('partner_paid', models.BooleanField(default=False)),
                ('added_from_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checkout.cart')),
            ],
        ),
    ]
