# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packs', '0001_initial'),
        ('digitalitems', '0002_digitalitem_downloadable_downloadhistory_downloads_userdownloadablehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='added_from_digital_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packs.digitalpack'),
        ),
    ]
