# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitalitems', '0003_downloads_added_from_digital_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='added_from_subscription_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionpack'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='digitalitems.digitalitem'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='digitalitems.difile'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloadable', to='digitalitems.difile'),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='digitalitems.downloadable'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='derived_from_all',
            field=models.ManyToManyField(blank=True, related_name='derivatives_all', to='digitalitems.DigitalItem'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='derived_from_any',
            field=models.ManyToManyField(blank=True, related_name='derivatives_any', to='digitalitems.DigitalItem'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='files',
            field=models.ManyToManyField(blank=True, to='digitalitems.DIFile'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='root_downloadable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalitems.downloadable'),
        ),
        migrations.AddField(
            model_name='difile',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.partner'),
        ),
        migrations.AddIndex(
            model_name='userdownloadablehistory',
            index=models.Index(fields=['user', 'downloadable'], name='digitalitem_user_id_5618a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloads',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='one_purchase_record_per_user'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['user', 'file'], name='digitalitem_user_id_8775d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadable',
            constraint=models.UniqueConstraint(condition=models.Q(('file', None)), fields=('parent', 'folder'), name='unique_folder'),
        ),
    ]
