# Generated by Django 3.0.4 on 2020-07-15 23:49

from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from treebeard.numconv import NumConv
from wagtail.core.models import Page, Site

# Values as of treebeard 4.2.0
PATH_ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
PATH_STEP_LENGTH = 4
PATH_NUM_CONV_BASE_FUNC = NumConv(len(PATH_ALPHABET), PATH_ALPHABET).int2str


def path_num_conv(num):
    return PATH_NUM_CONV_BASE_FUNC(num).rjust(PATH_STEP_LENGTH, '0')


# see big comment below
def add_child(apps, parent_page, klass, **kwargs):
    """
    Replicate `Page.add_child` in migrations since it is not available in this context.
    Originaly from http://www.agilosoftware.com/blog/django-treebard-and-wagtail-page-creation/
    with a fix for the path.
    """

    content_type_class = apps.get_model('contenttypes.ContentType')
    page_content_type = content_type_class.objects.get(
        model=klass.__name__.lower(),
        app_label=klass._meta.app_label
    )

    url_path = '%s%s/' % (parent_page.url_path, kwargs.get('slug'))
    path = parent_page.path + path_num_conv(parent_page.numchild + 1)

    created_page = klass.objects.create(
        content_type=page_content_type,
        path=path,
        depth=parent_page.depth + 1,
        numchild=0,
        url_path=url_path,
        **kwargs
    )

    parent_page.numchild += 1
    parent_page.save()

    return created_page


def add_data(apps, schema_editor):
    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    CGTPage = apps.get_model('cgtinfo', 'CGTPage')
    cgtpage_content_type = ContentType.objects.get_for_model(CGTPage)

    # random note for future developers... if you're ever getting weird errors when migrating
    #    (like `AttributeError: 'NoneType' object has no attribute '_inc_path'"`)
    # it's possible that the "tree" of pages (implemented by the django-treebeard library)
    # on the root page is broken or incorrect (this can happen if tree updates happen without using
    # transactions.) In order to fix this, you have to get extra technical:
    #
    #  You must try to fix the broken tree structure:
    #     - open a shell, pull the root page for the site (using the code below)
    #     - call the find_problems() method. If it returns anything other than a tuple of 5 empty arrays,
    #       you can call the fix_tree() method, and the problems should be resolved.
    #     - if you're hitting these problems elsewhere, you might need to consult migration 0002
    #       and do this for the root node of the whole wagtail installation.
    #
    # Code in the library that provides more information:
    # https://github.com/django-treebeard/django-treebeard/blob/e3887791f3137c4868ea1895d98b578ec7087701/treebeard/mp_tree.py#L669-L817
    #
    # ~~~~ This note was written by Sam Weaver on July 15th, 2020, at 20:30 EDT.
    #
    # UPDATE from Sam on April 9th, 2021, at 19:09 EDT:
    #
    # Whe using Django's "migration models" from apps.get_model, they're fake. They don't have the add_child method.
    # Hacky solution from here: https://gist.github.com/loicteixeira/9e20d78d91b518bcbee9642874760c20
    # More context here: https://github.com/wagtail/wagtail/pull/4621

    Page = apps.get_model('wagtailcore.Page')
    Site = apps.get_model('wagtailcore.Site')
    HomePage = apps.get_model('cgtinfo', 'HomePage')
    HomePageFeatureColumn = apps.get_model('cgtinfo', 'HomePageFeatureColumn')

    # Delete the default homepage
    # If migration is run multiple times, it may have already been deleted
    # Page.objects.all().delete()
    Page.objects.filter(id=2).delete()

    # root = Page.get_first_root_node()
    homepage_content_type = ContentType.objects.get_for_model(HomePage)

    home = HomePage.objects.create(
        title="Home",
        draft_title="Home",
        slug="root",
        content_type_id=homepage_content_type.id,
        show_in_menus=True,
        path='00010001',
        depth=2,
        numchild=0,
        locale_id=1,
    )

    # if you're getting weird errors on this line when migrating, check migration 0006 for instructions
    # root.add_child(instance=home);

    c1 = HomePageFeatureColumn(page_id=home.id, body="""
    <h2> OpenCGaT</h2>
    <p>This is the open source version of CG&T</p>
    """)
    c1.save()

    Site.objects.all().delete()
    Site.objects.create(
        hostname="localhost",
        root_page_id=home.id,
        is_default_site=True,
    )


def delete_site(apps, schema_editor):
    HomePage = apps.get_model('cgtinfo', 'HomePage')
    HomePage.objects.all().delete()
    Site.objects.all().delete()
    root = Page.get_first_root_node()
    root.fix_tree()
    root.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cgtinfo', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_data, delete_site)
    ]
