# Generated by Django 4.2.3 on 2023-08-12 15:31

from django.db import migrations, models


def forward_func(apps, _):
    Cart = apps.get_model("checkout", "Cart")
    Cart.submitted.update(invoice_been_printed=True)


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        # This migration sets the default for all columns to true then changes the default to false for the future.
        migrations.AddField(
            model_name='cart',
            name='invoice_been_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
