# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('game_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.publisher'),
        ),
        migrations.AddField(
            model_name='format',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='game_info.game'),
        ),
        migrations.AddField(
            model_name='faction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='game_info.game'),
        ),
        migrations.AddField(
            model_name='faction',
            name='subfaction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfactions', to='game_info.faction'),
        ),
        migrations.AddField(
            model_name='edition',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='game_info.game'),
        ),
        migrations.AddField(
            model_name='containspieces',
            name='any_of',
            field=models.ManyToManyField(blank=True, related_name='contained_in_option', to='game_info.GamePieceVariant'),
        ),
        migrations.AddField(
            model_name='containspieces',
            name='of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contained_in', to='game_info.gamepiecevariant'),
        ),
        migrations.AddField(
            model_name='containspieces',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_pieces', to='shop.product'),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='game_info.game'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='factions',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='game_info.Faction'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='game_info.game'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='game_info.attributetype'),
        ),
    ]
