# Generated by Django 4.2.2 on 2023-06-10 20:00

from django.db import migrations, models
import images.PublicAzureStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.ImageField(storage=images.PublicAzureStorage.PublicAzureStorage, upload_to='images')),
                ('alt_text', models.CharField(blank=True, help_text='Used in screen readers for the visually impared.  Blank to default to filename', max_length=200, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
