# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('subscriptions', '0002_subscriptionpack_token'),
        ('user_list', '0001_initial'),
        ('checkout', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpack',
            name='user_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_list.userlist'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='subscriptiondata',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.cart'),
        ),
        migrations.AddField(
            model_name='subscriptiondata',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='subscriptiondata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioncampaign',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='partner.partner'),
        ),
        migrations.AddField(
            model_name='subscriberlist',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='subscriberlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriberdiscount',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='subscriptions.subscriptioncampaign'),
        ),
        migrations.AddField(
            model_name='subscriberdiscount',
            name='tier_req',
            field=models.ManyToManyField(to='subscriptions.SubscriptionTier'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontier',
            unique_together={('campaign', 'external_name'), ('campaign', 'tier_name')},
        ),
    ]
