# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount_codes', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='referrer_is_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='partnerdiscount',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_discounts', to='discount_codes.discountcode'),
        ),
        migrations.AddField(
            model_name='partnerdiscount',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.partner'),
        ),
    ]
