# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_codes', '0002_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='shop.Publisher'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='discount_codes.referrer'),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.cart'),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount_codes.discountcode'),
        ),
        migrations.AddField(
            model_name='codeusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
