# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='partner.partner')),
            ],
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveSmallIntegerField(default=0)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.SmallIntegerField()),
                ('applied', models.BooleanField(default=False)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.tokenbalance')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.item')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionpack')),
            ],
        ),
        migrations.CreateModel(
            name='TokenCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tokentransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('pack', None), _negated=True), fields=('balance', 'pack'), name='one_change_per_pack'),
        ),
        migrations.AddConstraint(
            model_name='tokencost',
            constraint=models.UniqueConstraint(fields=('item', 'token'), name='one_cost_per_token_per_item'),
        ),
        migrations.AddConstraint(
            model_name='tokenbalance',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='one_balance_per_token'),
        ),
    ]
