# Generated by Django 3.2.16 on 2022-11-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundcampaign',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.partner'),
        ),
        migrations.AddField(
            model_name='backer',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.crowdfundcampaign'),
        ),
        migrations.AddField(
            model_name='backer',
            name='linked_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.partnertransaction'),
        ),
        migrations.AddField(
            model_name='backer',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='entitled_backers', to='crowdfund.Reward'),
        ),
        migrations.AddField(
            model_name='backer',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdfund.crowdfundtier'),
        ),
        migrations.AddField(
            model_name='backer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backer_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
