# Generated by Django 4.2.2 on 2023-06-10 20:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import oscar.models.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realaddress', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', wagtail.fields.RichTextField()),
                ('retail_partner', models.BooleanField(default=False)),
                ('digital_partner', models.BooleanField(default=False)),
                ('crowdfunding_features', models.BooleanField(default=False)),
                ('phys_cut', models.FloatField(default=0.98)),
                ('digital_cut', models.FloatField(default=0.96)),
                ('enable_mto', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('hide', models.BooleanField(default=False)),
                ('acct_balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('acct_balance', djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('in_store_tax_rate', models.FloatField(default=0.055, help_text='Percent in decimal form( ex .055)')),
                ('css_filename', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9\\.]+\\.css$')])),
                ('favicon_path', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('partner_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('default_download_all', models.BooleanField(default=True)),
                ('address_and_hours_info', models.TextField(blank=True, null=True)),
                ('administrators', models.ManyToManyField(blank=True, related_name='admin_of', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Platform Charge', 'A fee from the platform'), ('Purchase', 'The purchase of an item on platform and the fees associated'), ('Manual', 'Manual adjustment (see comments)'), ('Payment', 'A payment of the account balance'), ('Subscription', 'A subscription charged to a user')], default=None, max_length=128, null=True, verbose_name='type')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_total_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('transaction_total', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='USD', max_digits=14, null=True)),
                ('transaction_subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('transaction_subtotal', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=14)),
                ('transaction_fees_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('transaction_fees', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=14)),
                ('applied_to_account', models.BooleanField(default=False)),
                ('balance_after_apply_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('balance_after_apply', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='USD', max_digits=14, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_summary', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
                ('summarized_in', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summarizing', to='partner.partnertransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realaddress.realcountry', verbose_name='Country')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='partner.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Partner address',
                'verbose_name_plural': 'Partner addresses',
                'abstract': False,
            },
        ),
    ]
