# Generated by Django 4.2.3 on 2023-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='favicon_path',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_banner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_logo',
        ),
        migrations.AddField(
            model_name='partner',
            name='static_prefix',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
