# Generated by Django 4.2.3 on 2023-07-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_partner_favicon_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='css_filename',
        ),
    ]
